<?php

return [
    // Header & Intro
    'title' => 'RRSP Loan: Maximize Your Tax Deduction',
    'subtitle' => 'Turbo-Charge Your Retirement',
    'intro_p1' => 'The RRSP Loan is an advantageous financial strategy for Canadian taxpayers. It is not just a loan, but a powerful lever to maximize your annual contributions to your Registered Retirement Savings Plan (RRSP).',
    'intro_p2' => 'Discover how to turn your taxes into savings and reach your retirement goals faster.',
    'btn_quote' => 'Apply Now',
    'btn_contact' => 'Contact Us',
    'btn_calc' => 'RRSP Loan Calculator',

    // How it works
    'how_title' => 'What is an RRSP Loan and How Does It Work?',
    'how_intro' => 'An RRSP Loan allows you to borrow funds to make larger RRSP contributions than you could with your current cash flow.',

    'step_1_title' => '1. The Loan',
    'step_1_desc' => 'You borrow funds from a financial institution to contribute immediately to your RRSP.',

    'step_2_title' => '2. The Tax Deduction',
    'step_2_desc' => 'These additional contributions generate a tax deduction that significantly reduces your income tax for the current year.',

    'step_3_title' => '3. The Investment',
    'step_3_desc' => 'The funds are invested within the RRSP to generate tax-sheltered growth.',

    // Benefits
    'benefits_title' => 'Strategic Benefits of the RRSP Loan',
    'benefits_subtitle' => 'A key tool to catch up on contribution room or bridge a cash flow gap.',

    'benefit_1_title' => 'Easier Repayment',
    'benefit_1_desc' => 'Use the tax refund generated by the tax deduction to repay part or all of the loan, reducing the debt burden.',

    'benefit_2_title' => 'Accelerated Growth',
    'benefit_2_desc' => 'By contributing earlier and more substantially, you benefit from long-term growth and compounding to grow your retirement savings faster.',

    'benefit_3_title' => 'Tax Optimization',
    'benefit_3_desc' => 'You immediately maximize the tax advantages offered by the Canadian government, turning tax into savings.',

    // FAQ
    'faq_title' => 'Frequently Asked Questions (FAQ)',

    'faq_q1' => 'Is an RRSP Loan always advantageous?',
    'faq_a1' => 'No. The benefit depends on the balance between your tax rate (the higher it is, the greater the tax benefit), your loan interest rate, and the expected return on your investments. It is advisable to consult a professional if you are in a high tax bracket.',

    'faq_q2' => 'What types of RRSP Loans are available?',
    'faq_a2' => 'Two main formats: the <strong>Instant RRSP Loan</strong> (for a quick contribution for the current year) and the <strong>RRSP Catch-Up Loan</strong> (to use your unused contribution room from previous years).',

    'faq_q3' => 'What are the associated risks?',
    'faq_a3' => '<strong>Return Risk:</strong> The investment could generate a return lower than the cost of the loan (interest). <strong>Debt Risk:</strong> You must ensure a solid repayment capacity.',

    'faq_q4' => 'Is RRSP Loan interest tax-deductible?',
    'faq_a4' => 'No. Interest paid on an RRSP Loan is not tax-deductible for individuals, unlike loans used for business or other investment purposes.',

    'faq_q5' => 'What is the typical repayment period?',
    'faq_a5' => 'Loans typically last from 12 months to 10 years, depending on the borrower\'s strategy. Anyone with available RRSP contribution room and meeting credit criteria is eligible.',

    'faq_q6' => 'Can an RRSP Loan help finance an HBP (Home Buyers\' Plan)?',
    'faq_a6' => 'Indirectly, yes. Funds contributed via the loan become RRSP capital, which can be withdrawn tax-free for the HBP (buying a first home). However, the RRSP Loan itself must be repaid independently.',

    // CTA Final
    'cta_title' => 'Optimize your retirement savings today!',
    'cta_text' => 'Calculate your tax deduction and discover if the RRSP Loan is the right strategy for you.',
    'cta_btn' => 'Start Now',

    // Blog
    'blog_title' => 'Advice Zone',
    'blog_subtitle' => 'Our articles to optimize your retirement.',
    'blog_no_article' => 'No articles available at the moment.',
    'read_more' => 'Read more',
];
